
services:

  postgres:
    build: sql
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      PGUSER: lake_admin
      PGDATABASE: lake
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 2s
      timeout: 2s
      retries: 5

  node:
    build: js
      #depends_on:
      #postgres:
      #condition: service_healthy
    ports:
      - 9000:9000
    develop:
      watch:
        - action: sync
          path: ./js/
          target: /code
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

volumes:
  database:
